services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8092:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: toysbubus
      POSTGRES_PASSWORD: "HF5MqYnOztEAHxsSsKkKAU5raIX1sbXk"
    volumes:
      - ./data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'
  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "tULkZGqL3hMsZTXIEwd0qNefhjxg-sZG"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: toysbubus_test
      POSTGRES_PASSWORD: "KFmauSvfjnAAJ0WDiiQ_Q2ZUiZawqCXe"
    volumes:
      - ./test_data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "XitzIz3e53qIxlx3cDmY_5rkiXo3LhtI"
    environment:
      - REDIS_REPLICATION_MODE=master

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: serverpod_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "8099:5050"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
